#https://www.mkdocs.org/user-guide/configuration/#
site_name: HEAL Data Packaging 
site_url: https://norc-heal.github.io/heal-data-pkg-guide
repo_url: https://github.com/norc-heal/heal-data-pkg-guide
nav:
  - What is a data package:
    - intro/index.md
    - Study files: intro/study-file.md
    - Standard data package metadata: intro/sdpmd.md
    - Shareable data package: intro/shareable.md
    #- The Resource Tracker: overview/resource.md

  - Create your data package:
    - fit/index.md
    - Best fit questions: fit/best-fit-questions.md
    - Best fit annotation recs: 
      - fit/best-fit-recs/index.md
      - Early, results-support, standard resources: fit/best-fit-recs/early-res-stand.md
      - Early, results-support, low resources: fit/best-fit-recs/early-res-low.md
      - Early, dataset-sharing, standard resources: fit/best-fit-recs/early-data-stand.md
      - Early, dataset-sharing, low resources: fit/best-fit-recs/early-data-low.md
      - Late, results-support, standard resources: fit/best-fit-recs/late-res-stand.md
      - Late, results-support, low resources: fit/best-fit-recs/late-res-low.md
      - Late, dataset-sharing, standard resources: fit/best-fit-recs/late-data-stand.md
      - Late, dataset-sharing, low resources: fit/best-fit-recs/late-data-low.md
    #- Your data sharing orientation: fit/data-sharing-orientation.md
    #- Your study stage: fit/study-stage.md
    #- Early in study: fit/guidance-1.md
    #- Late in study: fit/late.md
  
  - Prepare your data package for submission:
    - submit/index.md
    - Create an open-access now shareable data package: submit/open-access-now.md
    - Create an open-access by date shareable data package: submit/open-access-date.md
    - Create a managed-access now shareable data package: submit/managed-access-now.md
    - Create a managed-access by date shareable data package: submit/managed-access-date.md
  #- Annotation: 
  #  - Annotation Approaches: annot/index.md
  #  - Wholistic vs. Minimal: annot/introholmin.md
  #  - As you go vs. Top-down: annot/introaddtop.md

  - More information about data packaging:
    - overview/index.md
    - What is a data package?: overview/what.md
    - Who should create a data package?: overview/who.md
    - Why should you create a data package?: overview/why.md
    - Where should you create a data package?: overview/where.md
    - When should you start thinking about creating a data package?: overview/when.md
    - How should you create your data package?: overview/how.md

  - Guidance & Resources:
    - g-and-r/index.md
    - Guidance:
      - guidance/index.md
      - File org and naming: 
        - file-o-and-n/index.md
        - File organization: guidance/file-org.md
        - File naming: guidance/file-name.md
      - Deidentification: g-and-r/deid.md
      - Repository selection: g-and-r/repo.md
      - Research community-specific metadata standards: g-and-r/rescommet.md
    - Resources:
      - resources/index.md
      - Metadata schemas:
        - schemas/index.md
        - Study Overview: schemas/md_study_overview.md
        - Experiment Tracker: schemas/md_experiment_tracker.md
        - Resource Tracker: schemas/md_resource_tracker.md
        - Results Tracker: schemas/md_results_tracker.md
        - Data Dictionary: schemas/md_data_dictionary.md

  - Terms & Concepts: 
    - terms/index.md
    #- File Types: terms/files.md
    #- Holistic vs. Minimal Annotation: terms/holmin.md
    #- Add-as-you-go vs. Top-down Annotation: terms/addtop.md
    #- File org and naming: 
    #  - File organization: terms/name.md
    #  - File naming: terms/name.md
    #- Data sharing orientations: terms/sharing.md
    #- Metadata schemas:
    #  - Experiment Tracker: schemas/md_experiment_tracker.md
    #  - Resource Tracker: schemas/md_resource_tracker.md
    #  - Results Tracker: schemas/md_results_tracker.md
  #  - Metadata templates:
  #    - Overview: terms/standard-data-pkg-metadata.md
      

    #- Study-level Metadata:
    #  - Resource Tracker: terms/studylevel/resource.md
    #  - Experiment Tracker: terms/studylevel/exp.md
    #- File-level Metadata: terms/filelevel.md
    #- Documenting dependencies: terms/depend.md


theme:
  name: material
  palette:
    scheme: heal_platform
  font:
    text: Montserrat
  logo: assets/HEAL_Initiative_White-cropped.svg
  features:
    - navigation.indexes
    # Disable for now, as it causes problems with links to sections in Safari
    # https://github.com/squidfunk/mkdocs-material/issues/3797
    # - navigation.instant
    - navigation.indexes
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.tracking
    #- navigation.sections
    #- toc.integrate
  favicon: assets/heal_logo.png
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://github.com/norc-heal
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
   #   url_download: True
      check_paths: true
      base_path: docs

plugins:
  - search
  - mkdocs-video:
      is_video: True
  - external-markdown
  - drawio_file
  #- exclude:
   #   glob:
    #    - snippets/*
 # - snippets

# TODO: add footer (this may be included in the custom jinja template?)
#    [![](img/gen3.png)](https://ctds.uchicago.edu/gen3)[![](img/createdby.png)](https://ctds.uchicago.edu/)
#   [![image alt text](image URL link)](anchor link)

# function readMore() { var dots = document.getElementById("dots"); var moreText = document.getElementById("more"); var btnText = document.getElementById("read-more-btn"); var btnText = document.getElementById("read-more-explorer"); if (dots.style.display === "none") { dots.style.display = "inline"; btnText.innerHTML = "Read more"; moreText.style.display = "none"; } else { dots.style.display = "none"; btnText.innerHTML = "Read less"; moreText.style.display = "inline"; } }
